// <auto-generated />
using Brivia.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Brivia.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200514224203_AddCategoriesAndUsers")]
    partial class AddCategoriesAndUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Brivia.Web.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Brivia.Web.Data.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer1")
                        .IsRequired();

                    b.Property<string>("Answer2")
                        .IsRequired();

                    b.Property<string>("Answer3")
                        .IsRequired();

                    b.Property<string>("Answer4")
                        .IsRequired();

                    b.Property<int>("CorrectAnswer");

                    b.Property<int>("IdCategory");

                    b.Property<int>("IdUser");

                    b.Property<string>("Question")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Brivia.Web.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("Gain");

                    b.Property<int>("Lost");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("UserEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
